# Generated by Django 3.1.7 on 2021-03-10 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo_list", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todoitem",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="todolist",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
