# Generated by Django 3.1.7 on 2021-03-10 23:08

from django.db import migrations, models
import todo_list.models


class Migration(migrations.Migration):

    dependencies = [
        ("todo_list", "0002_auto_20210310_2232"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todoitem",
            name="due_date",
            field=models.DateTimeField(default=todo_list.models.one_week_hence),
        ),
        migrations.AlterField(
            model_name="todoitem",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="todolist",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="todolist",
            name="title",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
