# Generated by Django 3.1.7 on 2021-03-11 01:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo_list", "0003_auto_20210310_2308"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todoitem",
            old_name="list",
            new_name="todo_list",
        ),
        migrations.AddField(
            model_name="todoitem",
            name="created_date",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="todoitem",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
